[package]
name = "raytracer"
version = "0.1.0"
authors = ["Rik van Toor <rik.van.toor@gmail.com>"]

[dependencies]
sdl2 = { version = "0.31.0", features = ["bundled", "static-link"] }
cgmath = "0.16.1"
